/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function parse(input: string, options?: ParseOptions | undefined | null): any

export interface ParseOptions {
  /** Whether to parse as MDX */
  mdx?: boolean
  /** Whether to support GFM strikethrough with a single tilde */
  gfmStrikethroughSingleTilde?: boolean
  /** Whether to support math (text) with a single dollar */
  mathTextSingleDollar?: boolean
  /** Whether to enable basic MDX expression parsing */
  mdxExpressionParse?: boolean
  /** Whether to enable basic MDX ESM parsing */
  mdxEsmParse?: boolean
  /** Whether to support frontmatter */
  frontmatter?: boolean
}

export interface Section {
  /** Raw text content of the section */
  raw: string
  /** Type of the section (e.g., "heading", "paragraph", etc.) */
  type: string
  /** Position information */
  position?: any
}

export declare function splitIntoSections(input: string, options?: ParseOptions | undefined | null): Array<Section>
