/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function parse(input: string, options?: ParseOptions | undefined | null): any

export interface ParseOptions {
  /** Whether to parse as MDX */
  mdx?: boolean
  /** Whether to enable GitHub Flavored Markdown (GFM) constructs */
  gfm?: boolean
  /** Whether to support GFM strikethrough with a single tilde */
  gfmStrikethroughSingleTilde?: boolean
  /** Whether to support math (text) with a single dollar */
  mathTextSingleDollar?: boolean
  /** Whether to enable basic MDX expression parsing */
  mdxExpressionParse?: boolean
  /** Whether to enable basic MDX ESM parsing */
  mdxEsmParse?: boolean
  /** Whether to support frontmatter */
  frontmatter?: boolean
}

export declare function splitIntoSections(input: string, options?: ParseOptions | undefined | null): Array<any>
